### ISSUE TITLE
gggenes works not with plotly

### ISSUE THREAD

**Issue by MichWeb75** [wilkox/gggenes#10]
Hi, it would be absolutely a dream if the gggenes plot would be transformable to a plotly object.

```
library(ggplot2)
library(gggenes)
p <- ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +  geom_gene_arrow() +
  facet_wrap(~ molecule,scales="free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") + theme_genes()

p <- ggplotly(p)
```

Error in convertUnit(x, unitTo, "y", "dimension", "y", "dimension", valueOnly = valueOnly) :
  'x' argument must be a unit object

**Comment by wilkox** [comment]
Hi @MichWeb75, unfortunately plotly doesn't provide automatic support for custom geoms like geom_gene_arrow() ([see here for a discussion](https://plot.ly/r/reference)). It might be possible in the future to add support via a custom geom2trace method, but at first glance I can't see a straightforward way to implement this. Sorry.
