### ISSUE TITLE
Default Color

### ISSUE THREAD

**Issue by MichWeb75** [wilkox/gggenes#13]
Hi Wilkox,
I am try to set up a custom colour scheme using the default colours of gggenes. 
Which are your default colours, which you use appart from ColorBrewer::Set3 ?

**Comment by wilkox** [comment]
Hi @MichWeb75,

The fill colours are set by ggplot2 (including any `scale_` layers like `scale_fill_brewer()`), not gggenes. The scales package has a function that will generate the ggplot2 discrete fill scales based on the number of categories:

``` r
library(scales)
pal <- hue_pal()(10)
show_col(pal)
```

![](https://i.imgur.com/jknpf1t.png)

<sup>Created on 2019-07-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
