### ISSUE TITLE
Modify theme_genes 

### ISSUE THREAD

**Issue by AnRibo** [wilkox/gggenes#15]
Hi, nice extension! 
Just a question about theme_genes
I can modify everything in theme except for the grey central line, none of the line/axis code for ggplot themes seem to work?

**Comment by wilkox** [comment]
Hi,

Try `panel.grid.major.y`:

``` r
library(ggplot2)
library(gggenes)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes() %+replace% theme(
    panel.grid.major.y = element_line(colour = "red")
  )
```

![](https://i.imgur.com/MPFEdKb.png)

<sup>Created on 2019-10-19 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
