### ISSUE TITLE
Label genes above gene boxes

### ISSUE THREAD

**Issue by Batstaph** [wilkox/gggenes#16]
Thanks for the great prog. I have some good illustrations, but I want to produce an illustration of a phage, so having the gene names inside the gene boxes doesn't work. I have tried without success to find an easy way to add the names above the boxes. I wondered if you had any suggestions. Here is an example of what I am trying to achieve.

![image](https://user-images.githubusercontent.com/37119089/69966139-abd76680-150d-11ea-87f0-5cbe17bf9e80.png)

Thank you for your help

**Comment by wilkox** [comment]
Sorry it took me so long to reply to this. Here's one way you can add text above the arrows with `geom_text()`:

``` r
library(ggplot2)
library(gggenes)

example_genes$middle <- (example_genes$start + example_genes$end) / 2

ggplot(example_genes, aes(xmin = start, xmax = end, x = middle, y = molecule, 
                          fill = gene, label = gene)) +
  geom_gene_arrow(arrow_body_height = unit(1, "mm"), arrowhead_height = unit(1, "mm"), 
                  arrowhead_width = unit(1, "mm")) +
  geom_text(angle = 90, hjust = -0.2, size = 2) +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes() +
  scale_y_discrete(expand = expand_scale(mult = c(4, 14)))
```

![](https://i.imgur.com/TZAoKgW.png)

<sup>Created on 2019-12-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by Batstaph** [comment]
This worked really nicely,  thank you for taking the time to reply.

Kay

Kay Fountain B.Vet.Med MVS (Conservation Medicine) MRCVS
PhD Student
Ed Feil Lab
University of Bath

________________________________
