### ISSUE TITLE
Legend Size

### ISSUE THREAD

**Issue by mweberr** [wilkox/gggenes#17]
The font size of the legend is too large if many different genes are shown in the gggenes plot. Is it possible to change the size of the legend. I tried
```
theme(legend.text=element_text(size=9))
theme_genes(base_size=9)
```
None of them worked.

**Comment by wilkox** [comment]
Hi @MichWeb75, could you post a [reprex](https://reprex.tidyverse.org/index.html) with some example data showing the problem?
