### ISSUE TITLE
error with subgene colours on reverse arrows

### ISSUE THREAD

**Issue by kcm18** [wilkox/gggenes#19]
Plotting genes in forward direction with colouring of subgene segments the genes works, however fails when trying to plot the genes in reverse orientation with colouring of subgene segements  

e.g. 
ggplot(example, aes(xmin=example$start, xmax=example$end, y=example$molecule, forward=example$direction))+geom_gene_arrow(fill = "white") +geom_subgene_arrow(data = example,aes(xmin = example$start, xmax = example$end, y = example$molecule, fill = example$gene,xsubmin = example$submin, xsubmax = example$submax), color="black", alpha=.7) +theme_genes()

Warning message:
Subgene 1 (4492..4594) breaks boundaries of gene (4492..4594), skipping

**Comment by wilkox** [comment]
Thanks for the report @kcm18. Could you post the example code as a [reprex](https://reprex.tidyverse.org)? At the moment I can't replicate this bug because I don't have the `example` data frame.
