### ISSUE TITLE
README not rendering correctly

### ISSUE THREAD

**Issue by jonocarroll** [wilkox/gggenes#2]
The presence of README.html seems to be confusing github so it's not rendering the .md on landing. 

Great looking package BTW - I was just promoting it when the render issue was noted.

**Comment by wilkox** [comment]
Thanks so much for the heads up @jonocarroll!

**Comment by wilkox** [comment]
Interesting – I happened to have some tabs open showing earlier views of this and other repos, and they were rending the markdown README instead of the HTML, even though the HTML file was there. I guess a switch got flipped somewhere at GitHub this morning?
