### ISSUE TITLE
Combine gggenes with other ggplot?

### ISSUE THREAD

**Issue by awitney** [wilkox/gggenes#23]
Hi,

I have a sequence coverage plot for a region of several genes, i would like to combine with gggenes to show the gene arrangement overlayed or next to the coverage ggplot. 

Is this possible at all?

thanks

**Comment by wilkox** [comment]
Hi @awitney, this isn't directly supported in gggenes but you should be able to manage it with some other packages. I suggest either [patchwork](https://github.com/thomasp85/patchwork), which lets you composite multiple plots side-by-side, or have a look at a package under development called [gggenomes](https://thackl.github.io/gggenomes/).
