### ISSUE TITLE
Can we make these 

### ISSUE THREAD

**Issue by Unlock-ViV** [wilkox/gggenes#25]

**Comment by Unlock-ViV** [comment]
I just want to know is it possible to get the plot or representation for the genome architecture in a circular format instead of linear?

**Comment by wilkox** [comment]
Hey @Unlock-ViV, this is a planned feature but unfortunately not added yet. I'm going to close this issues as it's a duplicate of #7.

**Comment by Unlock-ViV** [comment]
okay, but can you suggest me how to go about it or this can be achieved?

**Comment by wilkox** [comment]
I'm not aware of any R package that can do this currently. You might want to have a look at [Circos](http://circos.ca).

**Comment by Unlock-ViV** [comment]
Thank you, I'll try that.
