### ISSUE TITLE
Gene orientation

### ISSUE THREAD

**Issue by adomingues** [wilkox/gggenes#3]
First of all, great work!

I would like to make three suggestions for the visualization:
- adding directionality to the arrows so that we could have for instance genB pointing to the right. The information could be added as an extra column in the data. 
- Draw genes as boxes, that is without arrows at all, for those situations when directionality is not important. 
- label the genes with their names directly or using a `ggreppel`-style approach. 

I know it is a small and recent package and you probably already have this in your todo, so consider this as :+1: vote for enhanced features. 

Cheers.

**Comment by wilkox** [comment]
Thanks for the suggestions @adomingues!

For arrow directionality, the arrows will always be drawn xmin → xmax.

```r
genes <- data.frame(
  molecule = c("forwards", "backwards"),
  start = c(1001, 2002),
  end = c(2002, 1001),
  gene = c("genA", "genA")
)

ggplot2::ggplot(genes, ggplot2::aes(xmin = start, xmax = end, y = molecule)) +
  gggenes::geom_gene_arrow()
```
![screen shot 2017-10-04 at 08 15 34](https://user-images.githubusercontent.com/726198/31149616-3b4b5e20-a8dc-11e7-9ba4-9296b7c00dbb.png)

I considered creating a separate aesthetic for direction, but the approach in the rest of ggplot2 is to infer directionality from start and end coordinates e.g. [geom_segment](http://ggplot2.tidyverse.org/reference/geom_segment.html).

Re. drawing genes as boxes, for now this can be achieved by modifying the arrow parameters:

```r
ggplot2::ggplot(genes, ggplot2::aes(xmin = start, xmax = end, y = molecule)) +
  gggenes::geom_gene_arrow(
    arrowhead_width = ggplot2::unit(0, "mm"),
    arrowhead_height = ggplot2::unit(3, "mm")
  )
```
![screen shot 2017-10-04 at 08 22 18](https://user-images.githubusercontent.com/726198/31149857-290fdcee-a8dd-11e7-98a8-9305ddc6de1b.png)

I'll keep this in mind though and might add an alias like `geom_gene_box` if I extend the package in the future.

Regarding labelling genes, I've added a new `geom_gene_label` in the latest dev release (v0.2.0.9002). Thanks for the suggestion! 
![readme-labelled_genes-1](https://user-images.githubusercontent.com/726198/31159833-a9c0da5c-a917-11e7-8e91-5f53aa29dd62.png)

**Comment by adomingues** [comment]
Thanks a lot @wilkox for the very quick reply and added features!

**Comment by wilkox** [comment]
@adomingues In case you're still interested in the gene directionality issue, the latest development release (v0.2.0.9003) adds a new `forward` aesthetic that lets you control the direction of genes independent of `xmin` and `xmax`. I'm not sure if this is the best way to implement this so I'd be glad to hear any feedback.

**Comment by adomingues** [comment]
Thank you for letting me know @wilkox, but I ended up using ggbio for my particular purpose. I will this in mind for future projects though.

**Comment by wipperman** [comment]
Hello! Fantastic package, I can see this being so useful in my work--thanks!

Regarding the gene directionality issue, unless I'm misunderstanding something above, I think the best way to approach this would be to add an option where the start/end are reversed as a function of a logical in another column. 

So in the 'example_genes' case, when I plot them using the tutorial parameters, all of the arrows are pointing to the right. But biologically, some (the genes that say reverse under strand) should be pointing to the left. The 'example_genes' data type is identical to the data type I'm working with (an output from RefSeq, so probably very common). It would be easiest if there was an option to just reverse the start/end numbers for you, if the direction indicates as such. I hope this makes sense! Thanks. 

head(example_genes)
molecule  start    end gene  strand
Genome5 405113 407035 genA forward
Genome5 407035 407916 genB forward
Genome5 407927 408394 genC forward
Genome5 408387 408737 genD reverse
Genome5 408751 409830 genE forward
Genome5 409836 410315 genF forward

**Comment by wilkox** [comment]
Hi @wipperman, thanks for your interest in the package! I think the `forward` aesthetic added in v0.3.0 is similar to what you're suggesting as it will set the direction of the gene based on a column of logical values. See [this section of the README](https://github.com/wilkox/gggenes#reversing-some-genes-with-the-optional-forward-aesthetic) for a description.

**Comment by wipperman** [comment]
I was actually thinking something where the 'molecule' would still be faceted as is. As a biology-person, I want to see the genes pointing in the orientation that they are intended to, rather than having all of the arrows pointing in the same direction. The code below should do that--let me know if this makes sense?

```{r}
example_genes <- example_genes %>% mutate(newV1=ifelse(strand == "reverse",start,end),
        newV3=ifelse(strand=="reverse",end,start),
        end=newV1,
        start=newV3) %>%  select(-newV1, -newV3)
dummies <- make_alignment_dummies(
  example_genes,
  ggplot2::aes(xmin = start, xmax = end, y = molecule, id = gene),
  on = "genE"
)

ggplot2::ggplot(example_genes, ggplot2::aes(xmin = start, xmax = end, y =
                                              molecule, fill = gene)) +
  geom_gene_arrow() +
  ggplot2::geom_blank(data = dummies) +
  ggplot2::facet_wrap(~ molecule, scales = "free", ncol = 1) +
  ggplot2::scale_fill_brewer(palette = "Set3") +
  theme_genes()
```{r}

![image](https://user-images.githubusercontent.com/16925318/49976510-54ad4000-ff10-11e8-8684-7109992ff0df.png)

**Comment by wilkox** [comment]
Sorry, but I'm still a bit confused about what you are trying to achieve. It seems like what you're describing is provided by the `forward` aesthetic:

``` r
library(gggenes)
library(ggplot2)

example_genes$strand <- example_genes$strand == "forward"
dummies <- make_alignment_dummies(
  example_genes,
  aes(xmin = start, xmax = end, y = molecule, id = gene),
  on = "genE"
)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene, forward = strand)) +
  geom_gene_arrow() +
  geom_blank(data = dummies, aes(forward = 1)) +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes()
```

![](https://i.imgur.com/JloMmwX.png)

<sup>Created on 2019-01-30 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

(Note that you need to give `geom_blank` a dummy `forward` aesthetic, otherwise ggplot will complain that there is no `strand` column in `dummies`.)

If I'm still misunderstanding what you're asking for, can I ask that you open it as a new issue and continue the conversation there?
