### ISSUE TITLE
Place gene label above gene?

### ISSUE THREAD

**Issue by bbimber** [wilkox/gggenes#32]
Hello,

I have been looking to an R package that does this for a very long time - this seems like a well done and highly useful package.

I have one question: is there a way to get the gene label placed above the gene?  this would be especially helpful with short genes, as it would allow the label to extend past the gene end.

Thanks for any help.

**Comment by wilkox** [comment]
Hi bbimber – unfortunately there's no easy way to do this with `geom_gene_label()`, although of course you can still use `geom_text()` to label genes.

**Comment by wilkox** [comment]
@bbimber you might also want to look at [this suggestion](https://github.com/wilkox/gggenes/issues/28#issuecomment-705570329) from another gggenes user.
