### ISSUE TITLE
Legend element border

### ISSUE THREAD

**Issue by mchiapello** [wilkox/gggenes#36]
Hello,
is there a way to make the legend element borders white instead of black? With "legend element" I mean the square containing the gene/subgene colour. 

Thank you,
M

**Comment by wilkox** [comment]
Hi @mchiapello, sorry it took me a while to get to this issue.

Legend keys will be drawn with the same aesthetics as the geom they relate to, which in this case is `geom_arrow()`. So one way to make the key borders white is to make the borders of the arrows white:

``` r
library(gggenes)
library(ggplot2)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow(colour = "white") +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3")
```

![](https://i.imgur.com/TSMODIT.png)

<sup>Created on 2021-03-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

If you want to keep the black borders around the arrows but still force the keys to be white, one option is to override the legend aesthetics with `guides()`:

``` r
library(gggenes)
library(ggplot2)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  guides(fill = guide_legend(override.aes = list(colour = "white")))
```

![](https://i.imgur.com/Fy04Kl5.png)

<sup>Created on 2021-03-20 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>
