### ISSUE TITLE
Plot virus genome with overlapping genes

### ISSUE THREAD

**Issue by jchariker** [wilkox/gggenes#37]
Hi David,
I am plotting gene regions on the Sars-CoV-2 genome, and several regions overlap. Is there any way that gggenes can offset the overlapping areas? This is often done in other visualizations. I have an example of the problem below. Orf1ab-LP is contained within Orf1a which is contained within Orf1ab. If these were offset vertically it would work well. 

molecule	gene	start	end	strand	orientation
Sars-CoV-2	5UTR	1	265	forward	1
Sars-CoV-2	Orf1ab-LP	266	805	forward	1
Sars-CoV-2	Orf1a	266	13483	forward	1
Sars-CoV-2	Orf1ab	266	21555	forward	1
Sars-CoV-2	Nsp2	806	2719	forward	1
Sars-CoV-2	Nsp3	2720	8554	forward	1
Sars-CoV-2	Nsp4	8555	10054	forward	1

I can separate the overlapping areas and put them in different genomes as in your example, but this is not ideal because they are too far apart. I think your plots are beautiful and I would love to use gggenes to visualize this genome.
Thanks for your help!
Julia

**Comment by thackl** [comment]
Hi Julia,

I don't think that this can be easily done with gggenes. And I hope David won't mind me advertising a different package, but have a look at [gggenomes](https://thackl.github.io/gggenomes/index.html) . It's loosely based on gggenes, and for it's `geom_gene` you can set `position="pile"` (or `position=position_pile(<more args>)`) to automatically offset overlapping genes.

The data.frame for the genes would have to look slightly different, columns would be: seq_id gene start end strand, with strand as "+/-".

Cheers
Thomas

**Comment by jchariker** [comment]
Thank you very much, Thomas! 
gggenomes handled the overlapping gene regions very well.
Julia

**Comment by wilkox** [comment]
Thanks Thomas – gggenomes is a great solution for this sort of plot.

**Comment by zhaoxvwahaha** [comment]
> Thank you very much, Thomas! gggenomes handled the overlapping gene regions very well. Julia

Hi @jchariker @wilkox ,
I also have the same problem, I used gggenes to show the genome structure with gene name on each gene, but didn't display the overlapping. Then I used gggenomes to show overlapping, but I don't know how to show the gene name on each gene and adjust the their sizes, I checked the help info but didn't work out, could you help to share your command?
