### ISSUE TITLE
vertical gene arrows?

### ISSUE THREAD

**Issue by pierrj** [wilkox/gggenes#38]
Hello,

I was wondering if anyone knew of a solution to rotate the gene arrows.

I am trying to make a dot plot with gene arrows on the x axis and y axis but am having trouble figuring out how to rotate the arrows to point vertically instead.

Any help would be greatly appreciated.

Thanks,
Pierre

**Comment by wilkox** [comment]
Hi Pierre, sorry it's taken me so long to get to this issue. I don't fully understand what you're trying to achieve; would you be able to sketch a picture of how you would like the final plot to look? Thanks!

**Comment by pierrj** [comment]
Hello, no worries. Here is what I had in mind:

![image (1)](https://user-images.githubusercontent.com/50971915/120224395-36c71900-c1f8-11eb-8143-fd72785929fd.png)

Basically, just a dot plot showing an alignment between two sequences, and on the x and y axis, the gene arrows corresponding to where annotated genes are in each of the two sequences.

It's been a little while now but I was trying to figure out how to rotate the ggarrows object so I could use ggarrange to make the figure. Since I couldn't figure this out, I started looking into using viewport and grobs instead but this got a bit too low level and tedious for me...

Anyways, just wondering if there is a way to rotate the ggarrows object. If not, no worries, I will just keep making the figures in Adobe Illustrator like I have been. Thanks!

**Comment by wilkox** [comment]
I've just pushed a new development version (04.1.9004) that adds support for drawing arrows in flipped coordinates by adding `coord_flip()`. You can install the new version by running `devtools::install_github("wilkox/gggenes")`.

``` r
library(ggplot2)
library(gggenes)
packageVersion("gggenes")
#> [1] '0.4.1.9004'

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene, label = gene)) +
  geom_gene_arrow() +
  geom_gene_label(min.size = 0) +
  geom_blank(data = example_dummies) +
  facet_wrap(~ molecule, scales = "free", nrow = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes_flipped() +
  coord_flip()
```

![](https://i.imgur.com/2QlBgGW.png)

<sup>Created on 2021-06-01 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

Let me know how you go!

**Comment by pierrj** [comment]
Fantastic, thank you!
