### ISSUE TITLE
Cut off the useless position of the map

### ISSUE THREAD

**Issue by Yu-Wang-uq** [wilkox/gggenes#39]
Hi, 
Thanks for the wonderful visualisation tool for gene arrow map. I have a 5 genome and I pick up the target genes, they are quite far from each other which make the plot unreadable. I wondering if there a way to cut off part off the location that not contain genes.
Thanks for your warm assisstance.

Best.
<img width="1302" alt="Screen Shot 2021-05-06 at 3 51 39 pm" src="https://user-images.githubusercontent.com/60381485/117248448-55e5bb80-ae83-11eb-9031-24befcf056ad.png">

**Comment by wilkox** [comment]
Hi @Yu-Wang-uq, thanks for your kind words about gggenes. Unfortunately as ggplot does not support split axes there is no easy way to do this. You could consider using my package [ggwrap](https://github.com/wilkox/ggwrap) which would allow you to wrap each genome across multiple rows.

**Comment by thackl** [comment]
You could have a look at the [`focus()`](https://thackl.github.io/gggenomes/reference/focus.html) function of gggenomes. gggenomes builds on ggenes. `focus()` lets you zoom in on neighborhoods around genes of interest.

**Comment by wilkox** [comment]
Thanks @thackl – I thought there must be a way to do this in gggenomes but somehow overlooked `focus()`!
