### ISSUE TITLE
Wrap genes to plot whole genome

### ISSUE THREAD

**Issue by dsladevt** [wilkox/gggenes#4]
We love your program!  I was wondering if there is a way to plot a whole genome (~2000 genes), but have it wrap around to make multiple lines instead of it all being on one line?  I guess we could do this manually by instead of making each line a genome just not labeling, but one line that wraps at a specified number of bases would be great.

Keep up the good work!

**Comment by wilkox** [comment]
Thanks for the suggestion! I don’t think there’s a simple way to implement this at the moment but I’ll see if I can get it into a future version.

**Comment by wilkox** [comment]
@dsladevt On the off-chance that this would still be useful to you – [I've just released a package that solves this issue](https://github.com/wilkox/ggwrap).

**Comment by ireneortega** [comment]
Is there a way to plot two graphs in the same area? I want to graph two plots (in one row or one column), each for a contig of the same genome. At the same time, I want to wrap genes with the function `ggwrap(plot, n)`. 

Whatever I try, I get this error:
```
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```

**Comment by wilkox** [comment]
[Patchwork](https://patchwork.data-imaginist.com) might be useful for this.
