### ISSUE TITLE
Scale showing the size of 1 kb

### ISSUE THREAD

**Issue by meizhao12** [wilkox/gggenes#41]
Hello!
Thanks for the great package to draw gene maps. Very helpful.
Is there a way to display a small scale showing the size of 1 kb?
Right now, the figure I got displays the scale from 0 to 15000, at the interval of 5000. I was wondering how to show the length of just 1 kb?
And is there a way to move the position of the scale line?

Also, right now I can display the gene name in or above the box. 
Is there a way to display the gene name "geneA" in the box, and also other features like the NCBI gene locus number "APS_1234" or the gene function "MFS transporter" above or below the box?

Thanks for the help!
Best,
Mei

**Comment by wilkox** [comment]
Hi @meizhao12, thanks for your interest in gggenes!

For your first question, could you please post a [reprex](https://reprex.tidyverse.org) of your current code?

For your second, I'm not sure how you're displaying the gene name above the box. However, if you want to add two separate sets of gene labels to a plot, you can just add two separate `geom_gene_label()` layers with different values for the 'label' aesthetic (e.g. one mapping 'label' to the gene name and the other mapping it to the locus number). If this doesn't make sense, please post a reprex of your current code and I can show you what to change.
