### ISSUE TITLE
R 3.6 requirement

### ISSUE THREAD

**Issue by khkk378** [wilkox/gggenes#42]
Hi! This looks to be a perfect match for us, but we are restricted to R 3.5.1. May I ask what functionality it is that requires 3.6? Looking at the commits it doesn't seem like there would be anything after you bumped the requirement from 3.3 to 3.6. Thanks!

**Comment by wilkox** [comment]
Hi @khkk378, at the moment I don't have any plans to make the package backwards compatible with older versions of R, but let me know if this is still an issue for you and I will take another look at it.
