### ISSUE TITLE
Circular View of genome

### ISSUE THREAD

**Issue by KatWillen** [wilkox/gggenes#45]
Hi,

I love gggenes and would also like to use it for my publication, but therefore I would/need like to show some genomes in their circular view. Is it possible to do so with gggene?

Best

Kat

**Comment by wilkox** [comment]
Hi Kat, currently this can't be done with gggenes (although I'm working on it). In the meantime you might want to look at [Circos](http://circos.ca/) or [plasmapR](https://github.com/BradyAJohnston/plasmapR).

**Comment by KatWillen** [comment]
Thank you for your fast respond. Another question:  Is it possible to break one genome into two rows? I have a very large one that is not visible nicely on one row.

Best

Katharina

**Comment by KatWillen** [comment]
Excuse me another question :) How do I decrease the space between the genome and the x-axis?

**Comment by wilkox** [comment]
To break the genome over multiple rows, you could try my [ggwrap package](https://github.com/wilkox/ggwrap).

There are a few things that determine the space between the genome and the x-axis, but the two easiest to control would be the total height of the plot (which is controlled by the output device), and the height of the gene arrows (which is controlled with the `arrow_body_height` argument to `geom_gene_arrow()`).
