### ISSUE TITLE
conflicts between "make_alignment_dummies()" and "forward" aesthetic

### ISSUE THREAD

**Issue by Tsingsjeen** [wilkox/gggenes#49]
# the gene cluster align with RDase_A
rdhA_center <- make_alignment_dummies(
  rdhs_cluster,
  aes(xmin = start, xmax = end, y = rdhs_tree.tip.label, id = gene), 
  on = "RDase_A")

rdhs_operon2 <- ggplot(rdhs_cluster, aes(xmin = start, xmax = end, y = rdhs_tree.tip.label,
                                              fill = gene, forward = orientation)) +
 geom_gene_arrow() +
  geom_blank(data = rdhA_center) +
  facet_wrap(~ rdhs_tree.tip.label, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes()

rdhs_operon2

##########
Error in FUN(X[[i]], ...) : object 'orientation' not found

**Comment by wilkox** [comment]
Hi @Tsingsjeen, could you please post this as a [reproducible example](https://reprex.tidyverse.org) including the data in `rdhs_cluster`? Thanks!

**Comment by MichWeb75** [comment]
Hi had a similar issue. You need to add the orientation also to the dummies :
`dummies$orientation <- 1`
