### ISSUE TITLE
Arrow direction

### ISSUE THREAD

**Issue by jasonserviss** [wilkox/gggenes#5]
A feature request/suggestion/question... It would be useful to be able to change the direction of the arrow (from pointing right to pointing left) in cases where the two separate DNA strands would need to be represented. Is this already possible? Would it be something that you think should/could be implemented?

**Comment by wilkox** [comment]
Thanks for the suggestion @jasonserviss. The latest development release (v0.2.0.9003) adds a new `forward` aesthetic that lets you control the direction of genes independent of `xmin` and `xmax`. I'm not sure if this is the best way to implement this so I'd be glad to hear any feedback.

**Comment by jasonserviss** [comment]
That turned out really nice! I think it allows more flexibility for different types of use cases. No comments on the implementation,  it is pretty common that strand is included as a separate field in most genomics annotation so that is easily used as the "forward" variable that you added. Thanks a lot!



```
data <- tibble(
  gene = c(
    "uc009zne.5", "uc009zne.5", "uc009zne.5", "uc009zne.5", "uc009zne.5", 
    "uc009zne.5", "uc009zne.5", "uc058oto.1", "uc058oto.1", "uc058otp.1", 
    "uc058otp.1", "uc009zne.5", "uc009zne.5", "uc009zne.5", "uc009zne.5", 
    "uc009zne.5", "uc009zne.5", "uc058oto.1", "uc058otp.1"
  ),
  start = c(
    53962307, 53964230, 53965963, 53966275, 53967268, 53968616, 
    53974897, 53973125, 53975180, 53973127, 53975180, 53964124, 
    53964283, 53966087, 53966377, 53967394, 53968756, 53973923, 
    53973927
  ),
  stop = c(
    53964124, 53964283, 53966087, 53966377, 53967394, 53968756, 
    53974956, 53973923, 53977643, 53973927, 53976419, 53964230, 
    53965963, 53966275, 53967268, 53968616, 53974897, 53975180, 
    53975180
  ),
  feature = c(
    "exon", "exon", "exon", "exon", "exon", "exon", "exon", "exon", 
    "exon", "exon", "exon", "intron", "intron", "intron", "intron", 
    "intron", "intron", "intron", "intron"
  ),
  strand = c(
    -1, -1, -1, -1, -1, -1, -1, 1, 1, 1, 
    1, -1, -1, -1, -1, -1, -1, 1, 1
  )
)

ggplot(data = NULL) +
  geom_gene_arrow(
    data = filter(data, feature == "exon"), 
    aes(xmin = start, xmax = stop, y = gene, forward = strand, fill = gene)
  ) +
  geom_segment(
    data = filter(data, feature == "intron"), 
    aes(x = start, xend = stop, y = gene, yend = gene)
  ) +
  ggthemes::theme_few() +
  ggthemes::scale_fill_ptol() +
  labs(y = "transcript", x = "Chromosome 12") +
  theme(legend.position = "top") +
  guides(fill = FALSE)
```

![gggenes](https://user-images.githubusercontent.com/11668021/32880992-eb199bf6-caaf-11e7-8db1-8081b47e21fd.png)
