### ISSUE TITLE
Equal scaling between different figures

### ISSUE THREAD

**Issue by dinahoch** [wilkox/gggenes#52]
Hi @wilkox,

Firstly thank you for the wonderful tool! I am not exaggerating when I say that gggenes has saved me hours of drawing arrows on Illustrator...

I am making several figures and would like the scale to be the same between them. Currently, the figures are all made to be the same length so that 10kb on one figure could be the length of 20kb on another. Is there a way of scaling all axes so that 10kb is a specific length in all figures?

Thank you again!

Dina

**Comment by wilkox** [comment]
Hi Dina, thanks for you kind words about gggenes!

It sounds like you are probably faceting the plot with the ggplot2 function `facet_wrap()` and the `scales = "free"` option. If you use `scales = "fixed"` instead, the x axis will be exactly the same in each facet, including the axis limits (i.e. where the axis starts and ends). This will work well if the genes are at similar locations. However, if the genes are far apart, they will not be very easy to discern:

``` r
library(ggplot2)
library(gggenes)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free_y", ncol = 1) +
  scale_fill_brewer(palette = "Set3")
```

![](https://i.imgur.com/a6mYPbC.png)

<sup>Created on 2022-03-24 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If there is at least one gene that is shared between all the molecules, you can use gggenes's `make_alignment_dummies()` function [as described in the README](https://americanfietser.home.blog) to align the molecules on this gene. This will ensure the x axis for each molecule is on the same scale, even if the plot is faceted, and even if there are different limits, i.e. 10 kb on one molecule will cover the same distance 'on paper' as in another molecule even if the genomic locations are far apart.

If neither of the above works, please post a [reprex](https://reprex.tidyverse.org) with some sample data showing your current plot and I'll show you how to generate a set of `geom_blank()` coordinates that will work.

**Comment by dinahoch** [comment]
Hi David,

Thank you for your email and for the help. I dealt with the genes being far apart by giving them false coordinates close to one another and then make_alignment_dummies(), which worked well. However, it might be nice for a future version to have e.g. 10kb take up a defined length so that this can be replicated between figures without having to run all examples together every time – let me know if that’s unclear! Thank you again for the wonderful tool.

Best,
Dina
