### ISSUE TITLE
Features without arrows

### ISSUE THREAD

**Issue by jimrybarski** [wilkox/gggenes#53]
Is it possible to plot genes without arrows? I'd like to be able to plot some non-coding elements such as transposon ends, or a region of interest where the transcriptional direction is unknown.

**Comment by wilkox** [comment]
You can achieve this by tweaking the arrow geometry:

``` r
library(ggplot2)
library(gggenes)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow(
    arrowhead_width = grid::unit(0, "mm"),
    arrowhead_height = grid::unit(3, "mm")
  ) +
  facet_wrap(~ molecule, scales = "free", ncol = 1) +
  scale_fill_brewer(palette = "Set3") +
  theme_genes()
```

![](https://i.imgur.com/Cn1ofpr.png)

<sup>Created on 2022-05-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>
