### ISSUE TITLE
Add feature fail.

### ISSUE THREAD

**Issue by YuWang07** [wilkox/gggenes#55]
Hi, 

Thanks for develop this amazing tools. I get trouble when using the geom_feature () commend. I am current using the V0.4.1.

`Error in geom_feature(data = features, aes(x = position, y = Genome, forward = forward)) : 
  could not find function "geom_feature"`

Could you please give some suggestions?

**Comment by wilkox** [comment]
Hi YuWang, the `geom_feature()` function is only in the development version of gggenes (the version on GitHub). You can install the development version with:

`devtools::install_github('wilkox/gggenes')`

**Comment by YuWang07** [comment]
Hi, David 

I reinstall&load this version but still get the same error.

**Comment by wilkox** [comment]
Can you post the code that produces the error as a [reprex](https://reprex.tidyverse.org)?
