### ISSUE TITLE
removing distance between line and arrows

### ISSUE THREAD

**Issue by esraagithub** [wilkox/gggenes#56]
hello

could you help me to remove this distance 
![Capture](https://user-images.githubusercontent.com/53595110/191923735-59c59f07-b47a-4931-9dc9-0c1d61fe7c3b.JPG)
considering my code like this
ggplot(df, aes(xmin = Start, xmax = End, y=BGC, 
                                                 fill = Category, forward = Orientation)) +
      geom_gene_arrow()+#arrowhead_height = unit(3, "mm"), arrowhead_width = unit(3, "mm"))+
      
      labs(x='Locus (bp)', y='', title=df_4gggenes$BGC[1]) +
      
      scale_fill_brewer( palette = "Set3", na.value=NA)+
      theme_genes() %+replace% theme(axis.title.x=element_text(),
                                     axis.ticks.y = element_blank(),
                                     axis.text.y=element_blank(),
                                     legend.direction="horizontal",
                                     legend.position="bottom")

**Comment by wilkox** [comment]
Hi @esraagithub, what is in the `df` data frame?

**Comment by esraagithub** [comment]
> Hi @esraagithub, what is in the `df` data frame?

like that
![Capture](https://user-images.githubusercontent.com/53595110/191998036-b3eac3de-62d2-4084-9277-918046e61aee.JPG)

**Comment by wilkox** [comment]
Thanks @esraagithub. It's still a bit hard for me to help you without extra information. Could you please create a [reprex](https://reprex.tidyverse.org) with your code? Thanks

**Comment by gdanetzk** [comment]
In case anyone else comes across this issue when conducting analysis with gggenes. I thought I would share my solution to the question posed here. Adding expand arguments to scale_y_continuous allows the user to remove the excess whitespace around the molecules that occur when faceting.  

```{r}
# No space below the bars but 10% above them
ggplot(mtcars) +
  geom_bar(aes(x = factor(cyl))) +
  scale_y_continuous(expand = expansion(mult = c(0, .1)))
```
