### ISSUE TITLE
Issues with theme_genes()

### ISSUE THREAD

**Issue by sakuragi0109** [wilkox/gggenes#58]
Hi everyone, 

I don't know what's wrong with my Rstudio, because whenever I try to use the theme_genes(), it always gives me the error: 
"Error in ggplot2::element_line(colour = "grey20", linewidth = 0.5) : 
  unused argument (linewidth = 0.5)" 

I don't know how to fix this, can anyone help me with this? Thank you so much!

**Comment by wilkox** [comment]
Hi @sakuragi0109, what version of ggplot2 are you using? You can run `packageVersion("ggplot2")` to find out.

**Comment by sakuragi0109** [comment]
Hi Wilkox, I've checked and updated my current ggplot2 package and it's worked. Thank you so much for your suggestion!!!!
