### ISSUE TITLE
Can you modify the length of the following genomic region

### ISSUE THREAD

**Issue by isunshine-cc** [wilkox/gggenes#61]
Can you modify the length of the following genomic region

**Comment by wilkox** [comment]
Hi @isunshine-cc, I think something went wrong posting this? Was there supposed to be some code or an image?

**Comment by isunshine-cc** [comment]
Because different genome have different length, so we want to use autoscale parameter to control the genomic region; at the same time, we want to autoscale the gene length. If there are two many genes in the genomic region, I want to scale it with fixed spacing, So  can you help me to solve this requirement?

**Comment by wilkox** [comment]
Could you post a [reprex](https://reprex.tidyverse.org) with the code you have currently?
