### ISSUE TITLE
Terminator point feature 

### ISSUE THREAD

**Issue by stephenturner** [wilkox/gggenes#62]
David: wonderful little package here. Thank you for releasing this, along with excellent documentation!

I'm trying to use gggenes as an alternative to [dnaplotlib](https://github.com/VoigtLab/dnaplotlib) to draw diagrams of cloning constructs. In a perfect world I'd be able to use the [SBOL visual glyphs](https://sbolstandard.org/visual-glyphs/), but in the meantime, a low-hanging fruit I'd like to be able to do is mark a point genetic feature with a "T", to indicate a termination site. Like this, in the diagram below, for the RBGpA site at the far right hand side:

![image](https://github.com/wilkox/gggenes/assets/460076/6984abb0-8468-4497-ae7c-fb63f6bc8d49)

I can get this far, but I'm wondering if it's possible to add a new geom or aesthetic mapping that could indicate whether a point feature would be a terminator / horizontal hash, similar to how the TRUE in the forward aesthetic works.

![image](https://github.com/wilkox/gggenes/assets/460076/89379f7d-8391-408b-bd16-06da71098450)

Reprex:

```r
genes <- tibble::tribble(
       ~seqname, ~feature, ~start,  ~end,     ~attr,
  "myconstruct",    "CDS",  1625L, 2695L,  "POU5F1",
  "myconstruct",    "CDS",  2768L, 3721L,    "SOX2",
  "myconstruct",    "CDS",  3794L, 5248L, "Klf4_i4",
  "myconstruct",    "CDS",  5327L, 6637L,     "Myc",
  "myconstruct",    "CDS",  7308L, 8018L, "mCherry"
  )

features <- tibble::tribble(
       ~seqname,       ~feature, ~start,  ~end,   ~attr, ~position, ~forward,
  "myconstruct",     "promoter",   954L, 1547L, "pTRET",    1250.5,     TRUE,
  "myconstruct",   "polylinker",  2696L, 2767L,   "T2A",    2731.5,       NA,
  "myconstruct",   "polylinker",  3722L, 3793L,   "T2A",    3757.5,       NA,
  "myconstruct",   "polylinker",  5249L, 5326L,   "F2A",    5287.5,       NA,
  "myconstruct",   "polylinker",  6721L, 7307L, "IRES2",      7014,       NA,
  "myconstruct", "polyA_signal",  8095L, 8150L, "RBGpA",    8122.5,       NA
  )

library(ggplot2)
library(gggenes)
ggplot(genes, aes(xmin=start, xmax=end, y=seqname, fill=attr, label=attr)) +
  geom_gene_arrow() +
  geom_gene_label() +
  geom_feature(data=features,
               aes(x=position, y=seqname, forward=forward)) +
  geom_feature_label(data=features,
                     aes(x=position, y=seqname, forward=forward, label=attr)) +
  theme_genes() +
  theme(legend.position = "none") +
  labs(x=NULL, y=NULL)

sessionInfo()
```

Session Info:

```
R version 4.2.3 (2023-03-15)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Ventura 13.4

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] gggenes_0.5.0 ggplot2_3.4.2

loaded via a namespace (and not attached):
 [1] rstudioapi_0.14  magrittr_2.0.3   tidyselect_1.2.0 munsell_0.5.0    colorspace_2.1-0 R6_2.5.1         rlang_1.1.0     
 [8] fansi_1.0.4      dplyr_1.1.1      tools_4.2.3      grid_4.2.3       gtable_0.3.3     utf8_1.2.3       cli_3.6.1       
[15] clipr_0.8.0      withr_2.5.0      tibble_3.2.1     lifecycle_1.0.3  farver_2.1.1     vctrs_0.6.1      ggfittext_0.10.0
[22] glue_1.6.2       labeling_0.4.2   stringi_1.7.12   compiler_4.2.3   pillar_1.9.0     generics_0.1.3   scales_1.2.1    
[29] pkgconfig_2.0.3 
```

**Comment by wilkox** [comment]
Thanks for introducing me to the SBOL glyphs. That might be a good roadmap for a full set of features to implement in this package.

For now I've added `geom_terminator()` and `geom_terminator_label()` in the development version just pushed. Let me know if you hit any issues.

``` r
library(tibble)
library(ggplot2)
library(gggenes)

genes <- tibble::tribble(
       ~seqname, ~feature, ~start,  ~end,     ~attr,
  "myconstruct",    "CDS",  1625L, 2695L,  "POU5F1",
  "myconstruct",    "CDS",  2768L, 3721L,    "SOX2",
  "myconstruct",    "CDS",  3794L, 5248L, "Klf4_i4",
  "myconstruct",    "CDS",  5327L, 6637L,     "Myc",
  "myconstruct",    "CDS",  7308L, 8018L, "mCherry"
  )

features <- tibble::tribble(
       ~seqname,       ~feature, ~start,  ~end,   ~attr, ~position, ~forward,
  "myconstruct",     "promoter",   954L, 1547L, "pTRET",    1250.5,     TRUE,
  "myconstruct",   "polylinker",  2696L, 2767L,   "T2A",    2731.5,       NA,
  "myconstruct",   "polylinker",  3722L, 3793L,   "T2A",    3757.5,       NA,
  "myconstruct",   "polylinker",  5249L, 5326L,   "F2A",    5287.5,       NA,
  "myconstruct",   "polylinker",  6721L, 7307L, "IRES2",      7014,       NA,
  )

terminators <- tibble::tribble(
       ~seqname,       ~feature, ~start,  ~end,   ~attr, ~position, ~forward,
  "myconstruct", "polyA_signal",  8095L, 8150L, "RBGpA",    8122.5,       NA
  )

ggplot(genes, aes(xmin = start, xmax = end, y = seqname, fill = attr, label = attr)) +
  geom_gene_arrow() +
  geom_gene_label() +
  geom_feature(data = features, aes(x = position, y = seqname, forward = forward)) +
  geom_feature_label(data = features,
                     aes(x = position, y = seqname, forward = forward, label = attr)) +
  geom_terminator(data = terminators, aes(x = position, y = seqname)) +
  geom_terminator_label(data = terminators,
                     aes(x = position, y = seqname, label = attr)) +
  theme_genes() +
  theme(legend.position = "none") +
  labs(x = NULL, y = NULL)
```

![](https://i.imgur.com/1JhKGpt.png)

<sup>Created on 2023-06-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by stephenturner** [comment]
Amazing. Thanks for such a quick response. Confirmed I have this working with 0.5.9001, and as implemented it does exactly what I needed 🌟 🚀 

Pondering the API for a moment. There's a little bit of an inconsistency in how promoters and terminators are implemented. Promoters are part of a `features` tibble, where the forward aesthetic is either TRUE (forward), FALSE (reverse), or NA (just a point marker, all plotted with `geom_feature[_label]()`. However, the terminator feature has its own geom. Would it make more sense to have either:

1. Terminators implemented in `geom_feature[_label]()` where the "T" aesthetic is controlled by another variable, in the same way that the `forward` argument works? 
1. Separate geoms for promoters, similar to how you've implemented `geom_terminator()`? 

Pros/cons to each approach. They both make promoters/terminators consistent. They both would allow for future glyphs (such as those in SBOL). #-1 requires additional annotation columns in a tibble, while #-2 would require the user split up their tibble into multiple tibbles based on the type of feature being plotted. 

(FYI my specific use case: I'm reading in a GFF and making plotting decisions based on the feature type annotated in the GFF).

**Comment by wilkox** [comment]
I've been thinking about this too over the last few days, in terms of the best way to implement the full set of SBOL glyphs. I want to preserve the ggplot2 grammar, and I think it's correct to consider each glyph as a distinct geom that could potentially have different aesthetic mappings, so this would require a separate `geom_<glyph>()` for each. 

However, it would also be useful to have a convenience function for a use case like yours, where you have a data frame of genetic features of various types with feature type encoded in a variable, and simple aesthetic mappings. It would be very tedious to have to split the data into separate data frames for each feature type and draw a separate geom layer for each.

My current rough plan:

- A separate `geom_<glyph>()` for each of the SBOL sequence feature glyphs (potentially adding the molecule and interaction glyphs later) 
- `geom_gene_arrow()` becomes a wrapper for `geom_CDS()` and soft deprecated
- `geom_feature()` becomes a wrapper for `geom_promoter()`/`geom_location()` and soft deprecated
- `geom_subgene_arrow()` becomes a wrapper for `geom_polypeptide_region()` and soft deprecated
- Continue to use the `forward` aesthetic to control the direction of directional glyphs. I've never been happy with this terminology. It conflates 'positively in sequence numeric location', 'in the direction of transcription'/'in the 3′ direction', and 'towards the right side of the plot', all of which are potentially different things. Worse, it will get even more confusing if I ever introduce support for double-stranded molecular backbones. However, I'm yet to come up with a better alternative. 'Upstream'/'downstream' has basically the same problems as 'forward'.
- Continue the pattern of `geom_gene_arrow()`/`geom_gene_label()` by having a separate `geom_<glyph>_label()` for each glyph (`geom_CDS_label()`, `geom_intron_label()` etc.). I think this is necessary to preserve the ggplot2 grammar, as a user might want to use different aesthetic mappings for glyphs and labels. `geom_gene_label()`, `geom_feature_label()`, and `geom_subgene_label()` would become wrappers and soft deprecated
- Each of the `geom_<glyph>()` layers would also accept a `label` aesthetic which draws a text label for the feature with sensible defaults
- A convenience geom that wraps all the glyphs and accepts a `type` aesthetic. This would cover the common situation described above. It would remove the flexibility of having different aesthetic mappings for different glyphs, as well as fine-tune control of glyph geometry, but it would still probably cover a large proportion of use cases. It could be called something like `geom_sequence_feature()` or `geom_genetic_feature()` which is cumbersome but unfortunately I've already used `geom_feature()`. Alternatively, I could call it `geom_feature()` and have it draw promoters or locations with the current `geom_feature()` interface if `type` is not mapped, but soft-deprecate this functionality. This is a bit of an ugly hack in the short term but I think long term it's the better choice.

I'd be interested to hear any ideas you have about this as you have obviously given it some thought and have a relevant use case.
