### ISSUE TITLE
Break strand in intra-CDS regions

### ISSUE THREAD

**Issue by JasminDeu** [wilkox/gggenes#65]
Hi,
Is there a way to break the strand in long intra-CDS regions, so the CDS become more prominent?

**Comment by wilkox** [comment]
There's no way to do this within gggenes, but here are a few options to consider: 
- You could generate separate plots for each CDS region and compose them with [the patchwork package](https://patchwork.data-imaginist.com)
- You could use [the ggbreak package](https://cran.r-project.org/web/packages/ggbreak/vignettes/ggbreak.html) to insert axis breaks, although note that broken axes are [somewhat frowned upon](https://stackoverflow.com/questions/7194688/using-ggplot2-can-i-insert-a-break-in-the-axis) as they distort the mapping between data and plot aesthetics and can be misleading
- I wrote [a package called ggwrap](https://github.com/wilkox/ggwrap) which takes a wide plot and wraps it over multiple rows, originally intended for plotting long sequences with gggenes

**Comment by JasminDeu** [comment]
Thank you!
