### ISSUE TITLE
How to prepare for gggenes

### ISSUE THREAD

**Issue by LeoWelter** [wilkox/gggenes#67]
Thanks for this beautiful package. One thing (I'm rather new to R), how do I get from a (NCBI) gff3 file to a similar object as the example genes. Maybe I'm missing something in the documentation. Could you or someone point me in the right direction? Note: I run bakta and pgap on my assemblies.

**Comment by wilkox** [comment]
Could you please attach the gff3 file or a working subset of it? I can show you how to convert it to a data frame suitable for gggenes.

**Comment by LeoWelter** [comment]
For example the gff3’s here
https://ftp.ncbi.nlm.nih.gov/genomes/refseq/archaea/Acidianus_infernus/latest_assembly_versions/GCF_009729545.1_ASM972954v1/GCF_009729545.1_ASM972954v1_genomic.gff.gz

Any gff3 under the refseq subdirectory should have the same format
See for a description:
https://ftp.ncbi.nlm.nih.gov/genomes/README_GFF3.txt

**Comment by wilkox** [comment]
Here's an example using the [ape package](http://ape-package.ird.fr) to read the gff3 file and the [tidyverse](https://www.tidyverse.org) to clean and prepare the data:

``` r
# Libraries
library(tidyverse)
library(gggenes)
library(ape) # Provides the read.gff() function
#> 
#> Attaching package: 'ape'
#> The following object is masked from 'package:dplyr':
#> 
#>     where

# Read and prepare the gff3 file
assembly <- read.gff("~/tmp/GCF_009729545.1_ASM972954v1_genomic.gff") %>%
  filter(start < 5000) %>%
  filter(type == "gene") %>%
  mutate(attributes = str_split(attributes, ";")) %>%
  mutate(attributes = map(attributes, ~ .x[2])) %>%
  mutate(attributes = map_chr(attributes, str_remove, "Name=")) %>%
  mutate(orientation = strand == "+")

# Plot gene map with gggenes
ggplot(assembly, aes(xmin = start, xmax = end, label = attributes, 
                     forward = orientation, y = 1)) +
  geom_gene_arrow() +
  geom_gene_label()
```

![](https://i.imgur.com/A0dvruc.png)

<sup>Created on 2023-09-09 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
