### ISSUE TITLE
An incomprehensible error

### ISSUE THREAD

**Issue by iMay1314** [wilkox/gggenes#69]
I tried drawing with sample code and sample data. The package was libraried without errors or warnings.
```
library(ggplot2)
library(gggenes)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
    geom_gene_arrow() +
    facet_wrap(~ molecule, scales = "free", ncol = 1) +
    scale_fill_brewer(palette = "Set3")
```
But something went wrong unexpectedly.
```
Error in grid.Call(C_convert, x, as.integer(whatfrom), as.integer(whatto),  : 
  Viewport has zero dimension(s)
```
There's nothing wrong with the data.
```
> head(example_genes)
  molecule gene start   end  strand orientation
1  Genome1 genA 15389 17299 reverse           1
2  Genome1 genB 17301 18161 forward           0
3  Genome1 genC 18176 18640 reverse           1
4  Genome1 genD 18641 18985 forward           0
5  Genome1 genE 18999 20078 reverse           1
6  Genome1 genF 20086 20451 forward           1
```
Can anyone help me explain why?

**Comment by wilkox** [comment]
This is an error you see sometimes when the drawing area of the graphics device (e.g. the window that the plot appears in) is too small, or sometimes it just seems to happen randomly the first time you use a device. Often just running the ggplot() call a second time is enough to fix the error. If this doesn't work, please tell me more about the environment you are running R in (e.g. what operating system, command line vs RStudio). A screenshot would be useful.

**Comment by tupatupa** [comment]
I and iMay encountered the same issue. I adjusted the window size as you suggested and also reran the code, but the problem still happens.  (Win11& R 4.3.2)
![gggenes](https://github.com/wilkox/gggenes/assets/151898125/864a5d4d-6704-4ef1-a51e-85aa0b31395d)

**Comment by iMay1314** [comment]
> This is an error you see sometimes when the drawing area of the graphics device (e.g. the window that the plot appears in) is too small, or sometimes it just seems to happen randomly the first time you use a device. Often just running the ggplot() call a second time is enough to fix the error. If this doesn't work, please tell me more about the environment you are running R in (e.g. what operating system, command line vs RStudio). A screenshot would be useful.

Thank you. It has been solved with your help.
