### ISSUE TITLE
How about an option to draw an interrupted X-axis?

### ISSUE THREAD

**Issue by dwinsemius** [wilkox/gggenes#71]
There's a new question (not mine) on StackOverflow that is requesting such a facility. 
https://stackoverflow.com/questions/77608461/is-there-a-way-to-shorten-long-intergenic-regions-in-gggenes

**Comment by wilkox** [comment]
This isn't something I will add to gggenes, for a couple of reasons:

- It's outside the scope of the package
- Axis breaks are [not consistent with the Grammar of Graphics](https://stackoverflow.com/questions/7194688/using-ggplot2-can-i-insert-a-break-in-the-axis) as they distort the mapping between data and plot aesthetics and can be misleading

However, you can still achieve this with ggplot2 in a few different ways:

- You could generate separate plots for each CDS region and compose them with [the patchwork package](https://patchwork.data-imaginist.com)
- You could use [the ggbreak package](https://cran.r-project.org/web/packages/ggbreak/vignettes/ggbreak.html) to insert axis breaks
- I wrote [a package called ggwrap](https://github.com/wilkox/ggwrap) which takes a wide plot and wraps it over multiple rows, specifically for plotting long sequences with gggenes
