### ISSUE TITLE
error: No "geom_terminator" functions

### ISSUE THREAD

**Issue by allen-zhan340** [wilkox/gggenes#73]
Dear profeessor:
i have met some problems:
My gggenes version: 
![image](https://github.com/wilkox/gggenes/assets/73383699/4ab0363a-4896-4940-b760-369fb5ffa09a)

And i use the example scripts, but it reports that   ""No "geom_terminator" functions"", the scripts are as follows: 
ggplot(example_genes_polar, aes(xmin = start, xmax = end, y = molecule, fill = gene, label = gene)) +
  geom_feature(
    data = example_features_polar,
    aes(x = position, y = molecule, forward = forward)
  ) +
  geom_feature_label(
    data = example_features_polar,
    aes(x = position, y = molecule, label = name, forward = forward)
  ) +
  geom_terminator(data = example_terminators_polar, aes(x = position, y = molecule)) +
  geom_terminator_label(data = example_terminators_polar, 
                        aes(x = position, y = molecule, label = name)) +
  geom_gene_arrow() +
  geom_gene_label() +
  scale_fill_brewer(palette = "Set3") +
  coord_polar() +
  scale_y_discrete(limits = c("", "Genome6", "Genome1"))  

Looking forward for your reply.

**Comment by wilkox** [comment]
Hi @allen-zhan340, `geom_terminator()` is only in the development version of gggenes (the version on GitHub, currently 0.5.1.9002), not the version on CRAN. To install the development version from GitHub run:

```r
devtools::install_github("wilkox/gggenes")
```

Then the code should work:

``` r
library(ggplot2)
library(gggenes)
packageVersion("gggenes")
#> [1] '0.5.1.9002'

ggplot(
  example_genes_polar,
  aes(xmin = start, xmax = end, y = molecule, fill = gene, label = gene)
) +
  geom_feature(
    data = example_features_polar,
    aes(x = position, y = molecule, forward = forward)
  ) +
  geom_feature_label(
    data = example_features_polar,
    aes(x = position, y = molecule, label = name, forward = forward)
  ) +
  geom_terminator(
    data = example_terminators_polar,
    aes(x = position, y = molecule)
  ) +
  geom_terminator_label(
    data = example_terminators_polar,
    aes(x = position, y = molecule, label = name)
  ) +
  geom_gene_arrow() +
  geom_gene_label() +
  scale_fill_brewer(palette = "Set3") +
  coord_polar() +
  scale_y_discrete(limits = c("", "Genome6", "Genome1"))
```

![](https://i.imgur.com/MSNCsKk.png)

<sup>Created on 2024-02-22 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>

**Comment by allen-zhan340** [comment]
@wilkox , thanks a lot, it works!
