### ISSUE TITLE
How to deal with larger length for the genes

### ISSUE THREAD

**Issue by Nitin123-4** [wilkox/gggenes#77]
if we have genes from different regions from the gene, which can range between 20-30 OR 200-300 MB in the chr. In this case the arrow is coming as line only.

input example is:

molecule	gene	start	end	strand	orientation
chr1	gene1	520345	525138	forward	0
chr1	gene2	905691	906008	reverse	1
chr1	gene3	1046272	1056485	reverse	1
chr1	gene4	1564710	1567770	reverse	1
chr1	gene5	3848040	3848498	forward	0

please help to plot this more clearly.

**Comment by wilkox** [comment]
Hi @Nitin123-4, there are a few ways of dealing with the problem of drawing distant genes (see [this issue](https://github.com/wilkox/gggenes/issues/71)):

- You could generate separate plots for each region of interest and compose them with [the patchwork package](https://patchwork.data-imaginist.com/)
- You could use [the ggbreak package](https://cran.r-project.org/web/packages/ggbreak/vignettes/ggbreak.html) to insert axis breaks
- I wrote [a package called ggwrap](https://github.com/wilkox/ggwrap) which takes a wide plot and wraps it over multiple rows, specifically for plotting long sequences with gggenes
