### ISSUE TITLE
How to use scale_colour_manual to specify color for individual genes

### ISSUE THREAD

**Issue by dongzhang0725** [wilkox/gggenes#79]
Dear Developer,

I am attempting to utilize `scale_colour_manual` to assign specific colors to gene categories in my plot. My current implementation is as follows:
```
scale_colour_manual(values = c("cox1" = "#A9E795", "trnC" = "#B7CDDB", "trnM" = "#DB55D7", "trnG" = "#5DE566"))
```

However, it appears that my approach is not yielding the expected results. Could you please advise on the correct method to manually specify colors for individual genes?

**Comment by wilkox** [comment]
Hi @dongzhang0725, I'm not sure what is going wrong here as this looks like the correct usage of `scale_colour_manual()`. Could you please post a full [reprex](https://reprex.tidyverse.org)? Thanks.

**Comment by dongzhang0725** [comment]
The example code also not work:
```
library(ggplot2)
library(gggenes)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
    geom_gene_arrow() +
    facet_wrap(~ molecule, scales = "free", ncol = 1) +
    scale_fill_brewer(palette = "Set3") +
    theme_genes() + 
    scale_colour_manual(values = c("genB" = "#A9E795", "genA" = "#B7CDDB", "genC" = "#DB55D7", "genD" = "#5DE566"))
```

**Comment by wilkox** [comment]
`fill` and `colour` have different meanings in ggplot2. For a polygon geom like `geom_gene_arrow()`, `fill` is the colour inside the polygon, while `colour` is the colour of the outline. So all you need to do is use `scale_fill_manual()` instead:

``` r
library(ggplot2)
library(gggenes)

ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
    geom_gene_arrow() +
    facet_wrap(~ molecule, scales = "free", ncol = 1) +
    scale_fill_brewer(palette = "Set3") +
    theme_genes() + 
    scale_fill_manual(values = c("genB" = "#A9E795", "genA" = "#B7CDDB", "genC" = "#DB55D7", "genD" = "#5DE566"))
#> Scale for fill is already present.
#> Adding another scale for fill, which will replace the existing scale.
```

![](https://i.imgur.com/oRB7Aaa.png)

<sup>Created on 2024-06-07 with [reprex v2.1.0](https://reprex.tidyverse.org)</sup>
