### ISSUE TITLE
extract polygons from plot

### ISSUE THREAD

**Issue by zdk123** [wilkox/gggenes#8]
Is it possible to extract the coordinates of the underlying polygons from the ggplot object?

```
p <- ggplot(example_genes, aes(xmin = start, xmax = end, y = molecule, fill = gene)) +
  geom_gene_arrow() +
  facet_wrap(~ molecule, scales = "free", ncol = 1)
layer_data(p)
```
only contains the original start/stop position.
thanks!

**Comment by wilkox** [comment]
There's no easy way to do this that I know of, as the arrow polygon coordinates are generated at drawing time by `makeContent.genearrowtree()` – they're not in the plot object. Further, the coordinates would be in the coordinate system of their individual viewports/panels, not the entire plot.

Do you mind if I ask what you want the coordinates for? There might be an easier way to achieve it.

**Comment by zdk123** [comment]
I am primarily motivated by the use of [interactive shiny plots](https://shiny.rstudio.com/articles/plot-interaction.html). The basic app is to click on a gene and have some metadata display underneath the plot. Use the brush tool to highlight a gene and the image regenerates, coloring other genes over a similarity threshold (precomputed with BLAST, for instance).

I've actually got this part working, but what I'd also like to have is highlighting at the sub-gene level. For instance, color just in the range of the local alignment. The way I would image doing this is extracting the polygon data from gggenes, throwing away points outside the hit range and overlaying a new geom_polygon. I could do this with rectangles, I think, but I don't want to lose the arrowheads.

thanks!

**Comment by zdk123** [comment]
I am following up because I solved my own problem by forking gggenes and adding a new geom called `geom_subgene_arrow`. The idea is to draw subgene polygons given the range of the subgene and gene, and compute, on the fly, the shape of where the arrowhead portions of the gene are.  Therefore, I've left the aesthetics `xmin` and `xmax` to be the endpoints of the gene and added `x` and `xend` to be the endoints of the subgene. All 4 aesthetics should be applied.

The idea is to plot a colorless layer of `geom_gene_arrows` and add over that a layer with subgene ranges (with a thin or no color border).

Here is a workable example that adds random subgenes to `example_genes`

```
devtools::install_github('zdk123/gggenes', ref='subgene')

example_genes$direction <- ifelse(example_genes$strand == "forward", 1, -1)
example_genes$gene_id <- as.character(seq_len(nrow(example_genes)))
## randomly assign the number of subgene segments
example_genes$n_segments <- rpois(nrow(example_genes),2)

## construct subgene endpoints uniformly within the gene ##
make_segments <- function(x) {
  if (x[3] == 0) return(NA)
  tmp <- sort(round(runif(x[3]*2, x[1], x[2])))
  data.frame(from=tmp[(1:length(tmp) %% 2)==1],
               to=tmp[(1:length(tmp) %% 2)==0])
}

segments <- apply(example_genes[,c('start','end','n_segments')], 1, make_segments)
names(segments) <- 1:nrow(example_genes)

## remove genes with no subgenes ##
segments <- Filter(function(x) !any(is.na(x)), segments)
## segment list to data.frame
seg_df <- reshape2::melt(segments, id.vars=c('from', 'to'))
colnames(seg_df)[3] <- 'gene_id'

## join gene data to subgene segments
seg_df <- dplyr::left_join(seg_df, example_genes)

ggplot2::ggplot(example_genes,
                ggplot2::aes(xmin = start, xmax = end, y = molecule,
                             forward = direction)) +
  ggplot2::facet_wrap(~ molecule, scales = "free", ncol = 1) +
  geom_gene_arrow(fill='white') +
  geom_subgene_arrow(data=seg_df,
    ggplot2::aes(xmin = start, xmax = end, y = molecule, fill = gene,
                 forward = direction, x=from, xend=to), color='black', alpha=.7) +
  theme_genes()
```

The new geom is here:
https://github.com/zdk123/gggenes/blob/subgene/R/geom_subgene_arrow.R

The trick is to create either a 4 or 8 point polygon depending on where the subgene starts/ends before the flange. Depending on that you compute the new y position based on the bisected right triangle.

If you accept contributions to the gggenes package, I can add docs and create a PR - assuming also that anybody would find this useful.

**Comment by wilkox** [comment]
This is fantastic! Please submit this as a PR if you have the time. The only major change I would request (other than documentation and tests) would be to call the new aesthetics `xsubmin` and `xsubmax`, for consistency and for future-proofing against potential geoms that might use `x` to locate a point feature (e.g. restriction enzyme site).

**Comment by zdk123** [comment]
makes sense. I will work on it this week.
