### ISSUE TITLE
Orientation of genes with gene alignment 

### ISSUE THREAD

**Issue by soldatsm** [wilkox/gggenes#81]
Hi. Is it possible to use `make_alignment_dummies()` and show the gene direction with `forward=`? I try to do this, but I get an error. 
```
ERROR while rich displaying an object: Error in `geom_blank()`:
! Problem while computing aesthetics.
ℹ Error occurred in the 2nd layer.
Caused by error:
! object 'strand' not found
```

I try to draw my loci with that code:
```
dummies <- make_alignment_dummies(
  locuses,
  aes(xmin = start, xmax = end, y = contig, id = gene, forward = strand),
  on = "IclR"
)

my_plot <- ggplot(
    locuses,
    aes(xmin = start, xmax = end, y = contig, fill=gene, forward = strand)
  ) +
  geom_gene_arrow(arrowhead_height = unit(3, "mm"), arrowhead_width = unit(1, "mm")) +
  geom_blank(data = dummies) +
  scale_fill_manual(values = cols)+
  facet_wrap(~contig, scales = "free", ncol = 1)+
  theme_genes()
```

Thank you for your help and the package!

**Comment by wilkox** [comment]
Hi @soldatsm, could you try running `make_alignment_dummies()` without the forward aesthetic? i.e.:

```R
dummies <- make_alignment_dummies(
  locuses,
  aes(xmin = start, xmax = end, y = contig, id = gene),
  on = "IclR"
)

```

If that doesn't work, could you please post a [reprex](https://reprex.tidyverse.org) including the data in `locuses`? Thanks.

**Comment by soldatsm** [comment]
Okay... I just added `dummies$strand <- 1`, and it fixed everything. I don't know what exactly it does, but it works.

**Comment by soldatsm** [comment]
Thanks anyway
