### ISSUE TITLE
Unable to draw gene arrow in polar coordinates

### ISSUE THREAD

**Issue by lingrongjin** [wilkox/gggenes#82]
Hi David,

I installed the development version of gggenes (package version: ‘0.5.1.9002’) but I still can't get the example code for drawing gene arrow in polar coordinates to work. After loading the developmental version of gggenes, it still produced the error "could not find function "geom_terminator". If I comment out the geom_terminator line, it gave another error: Error in `geom_gene_arrow()`:
! Problem while converting geom to grob.
ℹ Error occurred in the 3rd layer.
Caused by error in `$<-.data.frame`:
! replacement has 0 rows, data has 18
The code works if I don't use coord_polar(). I'm wondering if you have any idea on how to solve this issue? 

Thanks,
Karen

**Comment by wilkox** [comment]
Hi Karen, I wasn't able to reproduce this error with the development version of gggenes. Could you please post a [reprex](https://reprex.tidyverse.org)? Thanks

**Comment by lingrongjin** [comment]
Hi David, I re-ran the code and somehow it worked today! It may have something to do with the Rstudio server the other day, but thanks for your reply!
